//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aklion.Crm.Dao.User {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aklion.Crm.Dao.User.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert dbo.[User]
        ///(
        ///	[Login],
        ///	PasswordHash,
        ///	Email,
        ///	Phone,
        ///	Surname,
        ///	[Name],
        ///	Patronymic,
        ///	Gender,
        ///	BirthDate,
        ///	IsEmailConfirmed,
        ///	IsPhoneConfirmed,
        ///	IsLocked,
        ///	IsDeleted,
        ///	AvatarUrl,
        ///	CreateDate,
        ///	ModifyDate
        ///)
        ///values
        ///(
        ///	@Login,
        ///	@PasswordHash,
        ///	@Email,
        ///	@Phone,
        ///	@Surname,
        ///	@Name,
        ///	@Patronymic,
        ///	@Gender,
        ///	@BirthDate,
        ///	@IsEmailConfirmed,
        ///	@IsPhoneConfirmed,
        ///	@IsLocked,
        ///	@IsDeleted,
        ///	@AvatarUrl,
        ///    getdate(),
        ///    null
        ///);
        ///
        ///select
        ///	scope_identity();.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete
        ///	from dbo.[User]
        ///	where Id = @id;.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select top 1
        ///	Id,
        ///    [Login],
        ///    PasswordHash,
        ///    Email,
        ///    Phone,
        ///    Surname,
        ///    [Name],
        ///    Patronymic,
        ///    Gender,
        ///    BirthDate,
        ///    IsEmailConfirmed,
        ///    IsPhoneConfirmed,
        ///    IsLocked,
        ///    IsDeleted,
        ///    AvatarUrl,
        ///    CreateDate,
        ///    ModifyDate
        ///	from dbo.[User]
        ///	where Id = @id;.
        /// </summary>
        internal static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select top 1
        ///	Id,
        ///    [Login],
        ///    PasswordHash,
        ///    Email,
        ///    Phone,
        ///    Surname,
        ///    [Name],
        ///    Patronymic,
        ///    Gender,
        ///    BirthDate,
        ///    IsEmailConfirmed,
        ///    IsPhoneConfirmed,
        ///    IsLocked,
        ///    IsDeleted,
        ///    AvatarUrl,
        ///    CreateDate,
        ///    ModifyDate
        ///	from dbo.[User]
        ///	where Email = @email;.
        /// </summary>
        internal static string GetByEmail {
            get {
                return ResourceManager.GetString("GetByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select top 1
        ///	Id,
        ///    [Login],
        ///    PasswordHash,
        ///    Email,
        ///    Phone,
        ///    Surname,
        ///    [Name],
        ///    Patronymic,
        ///    Gender,
        ///    BirthDate,
        ///    IsEmailConfirmed,
        ///    IsPhoneConfirmed,
        ///    IsLocked,
        ///    IsDeleted,
        ///    AvatarUrl,
        ///    CreateDate,
        ///    ModifyDate
        ///	from dbo.[User]
        ///	where [Login] = @login;.
        /// </summary>
        internal static string GetByLogin {
            get {
                return ResourceManager.GetString("GetByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	Id,
        ///    [Login]	as [Value]
        ///	from dbo.[User]
        ///	where IsLocked = 0
        ///		and IsDeleted = 0
        ///		and [Login] like @pattern + &apos;%&apos;;.
        /// </summary>
        internal static string GetForAutocompleteByLoginPattern {
            get {
                return ResourceManager.GetString("GetForAutocompleteByLoginPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	count(0)
        ///	from dbo.[User]
        ///	where @IsSearch = 0 or
        ///		((coalesce(@Id, 0) = 0 or Id = @Id)
        ///			and (coalesce(@Login, &apos;&apos;) = &apos;&apos; or [Login] like @Login + &apos;%&apos;)
        ///			and (coalesce(@Email, &apos;&apos;) = &apos;&apos; or Email like @Email + &apos;%&apos;)
        ///			and (coalesce(@Phone, &apos;&apos;) = &apos;&apos; or Phone like @Phone + &apos;%&apos;)
        ///			and (coalesce(@Surname, &apos;&apos;) = &apos;&apos; or Surname like @Surname + &apos;%&apos;)
        ///			and (coalesce(@Name, &apos;&apos;) = &apos;&apos; or [Name] like @Name + &apos;%&apos;)
        ///			and (coalesce(@Patronymic, &apos;&apos;) = &apos;&apos; or Patronymic like @Patronymic + &apos;%&apos;)
        ///			and (coa [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetPagedList {
            get {
                return ResourceManager.GetString("GetPagedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на if(exists(select 1 from dbo.[User] where [Email] = @email))
        ///	select convert(bit, 1);
        ///else
        ///	select convert(bit, 0);.
        /// </summary>
        internal static string IsExistByEmail {
            get {
                return ResourceManager.GetString("IsExistByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на if(exists(select 1 from dbo.[User] where [Login] = @login))
        ///	select convert(bit, 1);
        ///else
        ///	select convert(bit, 0);.
        /// </summary>
        internal static string IsExistByLogin {
            get {
                return ResourceManager.GetString("IsExistByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на if(exists(select 1 from dbo.[User] where [Phone] = @phone))
        ///	select convert(bit, 1);
        ///else
        ///	select convert(bit, 0);.
        /// </summary>
        internal static string IsExistByPhone {
            get {
                return ResourceManager.GetString("IsExistByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update dbo.[User]
        ///	set [Login] = @Login,
        ///		PasswordHash = @PasswordHash,
        ///		Email = @Email,
        ///		Phone = @Phone,
        ///		Surname = @Surname,
        ///		[Name] = @Name,
        ///		Patronymic = @Patronymic,
        ///		Gender = @Gender,
        ///		BirthDate = @BirthDate,
        ///		IsEmailConfirmed = @IsEmailConfirmed,
        ///		IsPhoneConfirmed = @IsPhoneConfirmed,
        ///		IsLocked = @IsLocked,
        ///		IsDeleted = @IsDeleted,
        ///		AvatarUrl = @AvatarUrl,
        ///		ModifyDate = getdate()
        ///	where Id = @id;.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
