//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aklion.Crm.Dao.Store {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aklion.Crm.Dao.Store.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert dbo.Store
        ///(
        ///	CreateUserId,
        ///    [Name],
        ///    ApiKey,
        ///    ApiSecret,
        ///    IsLocked,
        ///    IsDeleted,
        ///    CreateDate,
        ///    ModifyDate
        ///)
        ///values
        ///(
        ///	@CreateUserId,
        ///    @Name,
        ///    @ApiKey,
        ///    @ApiSecret,
        ///    @IsLocked,
        ///    @IsDeleted,
        ///    getdate(),
        ///    null
        ///);
        ///
        ///select
        ///	scope_identity();.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на delete
        ///	from dbo.Store
        ///	where Id = @id;.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select top 1
        ///	Id,
        ///	CreateUserId,
        ///    [Name],
        ///    ApiKey,
        ///    ApiSecret,
        ///    IsLocked,
        ///    IsDeleted,
        ///    CreateDate,
        ///    ModifyDate
        ///	from dbo.Store
        ///	where Id = @id;.
        /// </summary>
        internal static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	count(0)
        ///	from dbo.Store
        ///	where @IsSearch = 0 or
        ///		((coalesce(@Id, 0) = 0 or Id = @Id)
        ///			and (coalesce(@CreateUserId, 0) = 0 or CreateUserId = @CreateUserId)
        ///			and (coalesce(@Name, &apos;&apos;) = &apos;&apos; or [Name] like @Name + &apos;%&apos;)
        ///			and (coalesce(@ApiKey, &apos;&apos;) = &apos;&apos; or ApiKey like @ApiKey + &apos;%&apos;)
        ///			and (coalesce(@ApiSecret, &apos;&apos;) = &apos;&apos; or ApiSecret like @ApiSecret + &apos;%&apos;)
        ///			and (@IsLocked is null or IsLocked = @IsLocked)
        ///			and (@IsDeleted is null or IsDeleted = @IsDeleted)
        ///			and (@CreateDate is null o [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetPagedList {
            get {
                return ResourceManager.GetString("GetPagedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update dbo.Store
        ///    set CreateUserId = @CreateUserId,
        ///		[Name] = @Name,
        ///		ApiKey = @ApiKey,
        ///		ApiSecret = @ApiSecret,
        ///		IsLocked = @IsLocked,
        ///		IsDeleted = @IsDeleted,
        ///		ModifyDate = getdate()
        ///    where Id = @Id;.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
